=== windofthesky/jetspeed-2_svn/etc/xsd/jetspeed-portlet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2007 The Apache Software Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" 
	targetNamespace="http://portals.apache.org/jetspeed"
	xmlns:tns="http://portals.apache.org/jetspeed"
	xmlns:dc="http://www.purl.org/dc" 
	xmlns:js="http://portals.apache.org/jetspeed" 
	xmlns:p="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd">

  <!-- <xs:import namespace="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd" schemaLocation="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd"/>
  -->
  <xs:import namespace="http://www.purl.org/dc" schemaLocation="dublin-core.xsd"/>
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
             schemaLocation="http://www.w3.org/2001/xml.xsd"/>
             
                  
   
  <xs:element name="portlet-app">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="security-constraint-ref" type="xs:string"/>          
        <xs:group ref="tns:metadataGroup" minOccurs="0"/>
        <xs:element ref="tns:custom-portlet-mode" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:custom-window-state" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:portlet" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tns:services" minOccurs="0"/>
        <xs:element ref="tns:user-attribute-ref" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="version" type="xs:string"/>
    </xs:complexType>
  </xs:element>  
  
  <xs:element name="portlet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="portlet-name" type="xs:string"/>
        <xs:element name="security-constraint-ref" type="xs:string"/>
        <xs:group ref="tns:metadataGroup" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
      
  <xs:element name="custom-portlet-mode">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="mapped-name" type="xs:string"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="custom-window-state">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="mapped-name" type="xs:string"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>   
  
  <xs:element name="user-attribute-ref">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="name-link" type="xs:string"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>         
    
  <xs:element name="metadata">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute ref="xml:lang"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="services">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="js:service"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="service">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="metadataGroup">
     <xs:sequence>
       <xs:element ref="dc:creator" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:description" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:title" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:type" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:source" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:right" minOccurs="0" maxOccurs="unbounded"/>
         
       <xs:element ref="dc:relation" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:publisher" minOccurs="0" maxOccurs="unbounded"/>           
       <xs:element ref="dc:language" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:identifer" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:format" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:contributor" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="dc:coverage" minOccurs="0" maxOccurs="unbounded"/> 
       <xs:element ref="dc:subject" minOccurs="0" maxOccurs="unbounded"/>
       <xs:element ref="js:metadata" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
  </xs:group>
</xs:schema>

=== windofthesky/jetspeed-2_svn/etc/xsd/examples/jetspeed-portlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<portlet-app id="j2-admin" version="1.0"
    xmlns="http://portals.apache.org/jetspeed"
    xmlns:js="http://portals.apache.org/jetspeed"
    xmlns:dc="http://www.purl.org/dc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://portals.apache.org/jetspeed http://portals.apache.org/jetspeed-2/2.1/schemas/jetspeed-portlet.xsd">
     
    <js:security-constraint-ref>admin-only</js:security-constraint-ref>      

    <dc:creator>J2 Team</dc:creator>
    <dc:title>Jetspeed-2 Administration Portlets</dc:title>
    <dc:title xml:lang="en">Jetspeed-2 Administration Portlets</dc:title>
    
    <custom-portlet-mode>
      <name>mycustom</name>
      <mapped-name>mymap</mapped-name>
    </custom-portlet-mode>
    
    <custom-window-state>
      <name>popup</name>
      <mapped-name>solo</mapped-name> 
    </custom-window-state>

	<portlet>
        <portlet-name>LoginPortlet</portlet-name>
        <js:security-constraint-ref>users-1</js:security-constraint-ref>                                        
        <dc:creator>J2 Team</dc:creator>
        <dc:title>Login Portlet</dc:title>
    </portlet>

    <portlet>
        <portlet-name>LocaleSelector</portlet-name>
        <js:security-constraint-ref>users-1</js:security-constraint-ref>                                        
        <dc:creator>J2 Team</dc:creator>        
        <dc:title>Locale Selector Portlet</dc:title>
    </portlet>

	<js:services>        
        <js:service name='ApplicationServerManager'/>
        <js:service name='DeploymentManager'/>
		<js:service name='EntityAccessor'/>
        <js:service name='GroupManager'/>    
        <js:service name='PageManager'/>    
        <js:service name='PermissionManager'/>        
        <js:service name='PortalAdministration'/>        
        <js:service name='PortletFactory'/>        
        <js:service name='PortalAdministration'/>
        <js:service name='PortletRegistryComponent'/>
        <js:service name='PortalStatistics'/>        
        <js:service name="Profiler" />         
        <js:service name='RoleManager'/>
	    <js:service name='SearchComponent'/>                
        <js:service name="SSO" />                 
        <js:service name='UserManager'/>     
        <js:service name='DecorationFactory'/>        
	</js:services>
	
	<user-attribute-ref>
	  <js:name>my name</js:name>
	  <js:name-link>my link</js:name-link>
	  <js:description>my description</js:description>
	</user-attribute-ref>

</portlet-app>
